### ISSUE TITLE
Error while disassemble in some OS

### ISSUE THREAD

**Issue by JasonMo1** [Zeal8bit/Zeal-WebEmulator#7]
If you use zos v0.2.0 and set a breakpoint at 0x4000, there will be an error like this because there are nothing in the memory:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at hex (index.json:233:35)
    at hex8 (utils.js:242:19)
    at disassemble_memory (disassembler.js:311:28)
    at setASMView (panel.js:158:23)
    at updateAndShowRAM (panel.js:118:5)
    at updateRegistersHTML (panel.js:113:5)
    at breakpoint.js:81:21
```
I will fix this some commits later.

**Comment by JasonMo1** [comment]
Fixed at my repo.
